### ISSUE TITLE
Segfault when desktop is disabled and removing last link panel

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#161]
### System Information
Version: 1.0.10 from AppCenter
OS: elementary OS Juno 5.0

### Steps to reproduce
To see the segfault message launch Desktop Folder from the terminal.

1. Disable Panel Over Desktop, `killall com.github.spheras.desktopfolder` and relaunch Desktop Folder
2. Add a link panel
3. Remove/trash all other desktop windows
4. Remove the link panel

### Result
Desktop Folder will crash with a segmentation fault.

**Comment by aljelly** [comment]
Backtrace:

```
backtrace

#0  0x00007ffff6cd7230 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#1  0x00007ffff6cd4328 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#2  0x00007ffff77f210d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#3  0x00007ffff780512e in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#4  0x00007ffff780d715 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#5  0x00007ffff780e12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#6  0x00007ffff6f5b302 in gtk_window_set_application () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0

#7  0x00007ffff77f7da2 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#8  0x00007ffff77f95c0 in g_object_new_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#9  0x00007ffff77f9939 in g_object_new () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#10 0x000055555558169c in desktop_folder_folder_window_construct (object_type=93824996897456, manager=0x555555e6da70) at /home/aled/Misc/git-repos/desktopfolder/src/widgets/FolderWindow.vala:83

#11 0x00005555555820ce in desktop_folder_folder_window_new (manager=0x555555e6da70) at /home/aled/Misc/git-repos/desktopfolder/src/widgets/FolderWindow.vala:82

#12 0x00005555555adea2 in desktop_folder_folder_manager_real_create_view (self=0x555555e6da70) at /home/aled/Misc/git-repos/desktopfolder/src/logic/FolderManager.vala:88

#13 0x00005555555adf2e in desktop_folder_folder_manager_create_view (self=0x555555e6da70) at /home/aled/Misc/git-repos/desktopfolder/src/logic/FolderManager.vala:87

#14 0x00005555555adcf0 in desktop_folder_folder_manager_construct (object_type=93824996801840, application=0x555555892120, folder_name=0x555555c832b0 "My First Panel") at /home/aled/Misc/git-repos/desktopfolder/src/logic/FolderManager.vala:58

#15 0x00005555555ade88 in desktop_folder_folder_manager_new (application=0x555555892120, folder_name=0x555555c832b0 "My First Panel") at /home/aled/Misc/git-repos/desktopfolder/src/logic/FolderManager.vala:50

#16 0x0000555555563c58 in desktop_folder_app_sync_folders_and_notes (self=0x555555892120) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:314

#17 0x0000555555564c44 in desktop_folder_app_sync_folders_and_notes (self=0x555555892120) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:394

#18 0x0000555555565dbd in desktop_folder_app_desktop_changed (self=0x555555892120, src=0x555555a1ab20, dest=0x0, event=G_FILE_MONITOR_EVENT_DELETED) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:524

#19 0x00005555555656b0 in _desktop_folder_app_desktop_changed_g_file_monitor_changed (_sender=0x555555b6b8b0, file=0x555555a1ab20, other_file=0x0, event_type=G_FILE_MONITOR_EVENT_DELETED, self=0x555555892120) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:490

#20 0x00007ffff483ddae in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6

#21 0x00007ffff483d71f in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6

#22 0x00007ffff77f2ced in g_cclosure_marshal_generic_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#23 0x00007ffff77f2346 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#24 0x00007ffff780d9ff in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#25 0x00007ffff780e12f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0

#26 0x00007ffff7b1ef99 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

#27 0x00007ffff7518387 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0

#28 0x00007ffff75185c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0

#29 0x00007ffff751864c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0

#30 0x00007ffff7ad8eaa in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0

#31 0x000055555556630c in desktop_folder_app_main (args=0x7fffffffd968, args_length1=1) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:556

#32 0x0000555555566355 in main (argc=1, argv=0x7fffffffd968) at /home/aled/Misc/git-repos/desktopfolder/src/Application.vala:543

```

**Comment by spheras** [comment]
this happens just removing the last panel (not needed to be a link panel)

**Comment by fossfreedom** [comment]
Different types of users I guess.  For users coming from budgie and for ubuntu gnome shell users they expect a desktop to interact with. They don't need a hello type panel.  I am guessing since you are posing the question that elementary users are used to the fact that the default desktop you don't interact with... and hence the hello panel is perhaps needed for these users to highlight the fact that you can do something extra now.

**Comment by aljelly** [comment]
That sounds reasonable. So:
- For elementary users, create the "My First Panel" panel on first ever launch (to prevent #149 from happening), don't create it after that unless panel over desktop is disabled (you can't create any new Desktop Folder windows otherwise). In the situation where panel over desktop is disabled, perhaps call any subsequent ones "New Panel".
- Meanwhile for Ubuntu Budgie (or any other distro that people assume there's going to be a desktop), don't make the "My First Panel" panel. Implement a simple config switch in Desktop Folder and then some compile or runtime config option can be done by the distro/packager (if that's not already being done for some other part of Desktop Folder).

@spheras

**Comment by spheras** [comment]
@aljelly , the first time dekstopfolder is launched the .desktopfolder file for the ~/Desktop is created. This time I could force the creation of the "My First Panel". Only that time (when the first .desktopfolder is created).  
@fossfreedom, So, you think this "only one time My First Panel" is not necessary for other distributions, don't you? I'm not sure, maybe this is the first time budgie users have panels over desktop and they don't know that. Anyway, I could restore that setting you did to avoid that "My First Panel" if you agree.

**Comment by fossfreedom** [comment]
Yes please - lets restore it - default to create the "My First Panel"

For UB I will override that so that "My First Panel" doesn't appear.
